### ISSUE TITLE
建议：在CellBody中也加入CellFooter默认Text的处理？

### ISSUE THREAD

**Issue by liyatang** [maskzh/rn-weui#8]
在CellBody中
https://github.com/maskzh/rn-weui/blob/master/src/Cell/CellBody.js#L18
加入如下行为
https://github.com/maskzh/rn-weui/blob/master/src/Cell/CellFooter.js#L24

毕竟CellBody为文本的概率是很大的。  大神怎么看？

**Comment by maskzh** [comment]
感谢提供建议，大神不敢当哈。
现在如果子元素为文本，就自动包裹 CellText，不需要手动去包裹了
